# Generated by Django 4.2.1 on 2023-05-14 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_question_options_alter_question_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.RemoveField(
            model_name='question',
            name='voter',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
